- name: install keystone packages
  apt: name={{item}} state=present
  with_items:
    - glance

- name: remove default sqlite database file
  file: state=absent path=/var/lib/glance/glance.sqlite

- include: database.yml

- name: enable version 1 of the images API
  lineinfile: dest=/etc/glance/glance-api.conf regexp="^(#\s*)?enable_v1_api" line="enable_v1_api=true"

- name: enable version 2 of the images API
  lineinfile: dest=/etc/glance/glance-api.conf regexp="^(#\s*)?enable_v2_api" line="enable_v2_api=true"

- name: edit the admin tenant name in glance-api.conf
  lineinfile: dest={{item}} regexp="^admin_tenant_name" line="admin_tenant_name = service"
  with_items:
    - /etc/glance/glance-api.conf
    - /etc/glance/glance-registry.conf

- name: edit the admin user name in glance-api.conf
  lineinfile: dest={{item}} regexp="^admin_user" line="admin_user = glance"
  with_items:
    - /etc/glance/glance-api.conf
    - /etc/glance/glance-registry.conf  

- name: edit the admin password in glance-api.conf
  lineinfile: dest={{item}} regexp="^admin_password" line="admin_password = glance"
  with_items:
    - /etc/glance/glance-api.conf
    - /etc/glance/glance-registry.conf

- name: enable the paste_deploy config file
  lineinfile: dest=/etc/glance/glance-api.conf regexp="^(#\s*)?config_file" line="config_file = /etc/glance/glance-api-paste.ini" insertafter="^[paste_deploy]"

- name: enable the paste_deploy config file
  lineinfile: dest=/etc/glance/glance-registry.conf regexp="^(#\s*)?config_file" line="config_file = /etc/glance/glance-registry-paste.ini" insertafter="^[paste_deploy]"

- name: set flavor=keystone
  lineinfile: dest={{item}} regexp="^(#\s*)?flavor" line="flavor = keystone"
  with_items:
    - /etc/glance/glance-api.conf
    - /etc/glance/glance-registry.conf

- name: ensure sql_connection points to mysql
  lineinfile: dest={{item}} regexp="^sql_connection" line="sql_connection = mysql://${glance_db_user}:${glance_db_pw}@${db_host}/${glance_db}"
  with_items:
    - /etc/glance/glance-api.conf
    - /etc/glance/glance-registry.conf

- name: add the keystone pipeline section for glance-registry-paste
  lineinfile: dest=/etc/glance/glance-registry-paste.ini regexp="^\[pipeline:glance-registry-keystone\]" line="[pipeline:glance-registry-keystone]"

- name: add the pipeline definition for glance-registry-paste
  lineinfile: dest=/etc/glance/glance-registry-paste.ini regexp="^pipeline = authtoken context registryapp" line="pipeline = authtoken context registryapp" insertafter="^\[pipeline:glance-registry-keystone\]"


- name: restart glance-api
  service: name=glance-api state=restarted

- name: configure glance to use the Identity service
  lineinfile: dest=/etc/glance/glance-registry-paste.ini regexp="^pipeline =" line="pipeline = authtoken context registryapp"

- name: restart glance-registry 
  service: name=glance-registry state=restarted

- name: populate the database
  command: glance-manage db_sync

- name: restart glance registry and api services
  service: name={{item}} state=restarted
  with_items:
    - glance-registry
    - glance-api

- include: tests.yml

