- name: download Cirros 0.3.1 image
  command: chdir=/tmp creates=/tmp/cirros-0.3.1-x86_64-disk.img wget http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img
  environment: proxy_env

- name: create a new image
  glance_image: name="Cirros 0.3.1"
                container_format=bare disk_format=qcow2
                login_tenant_name={{os_tenant_name}}
                auth_url="http://{{keystone_host}}:35357/v2.0/"
                login_password="{{os_password}}"
                login_username="{{os_username}}"
                state=present
                file=/tmp/cirros-0.3.1-x86_64-disk.img

- name: clean up downloaded file
  file: state=absent path=/tmp/cirros-0.3.1-x86_64-disk.img
