---
  - include: playbooks/logstash.yml
  - include: playbooks/loadbalancer.yml
  - include: playbooks/galera.yml
  - include: playbooks/database.yml
  - include: playbooks/messaging.yml
  - include: playbooks/keystone-nodes.yml
  - include: playbooks/glance-nodes.yml
  - include: playbooks/network-nodes.yml
  - include: playbooks/mpio.yml
  - include: playbooks/cinder-nodes.yml
  - include: playbooks/controller-nodes.yml
  - include: playbooks/compute-nodes.yml
  - include: playbooks/reboot-all.yml
