---
# file: site.yml
  - include: database.yml
  - include: messaging.yml
  - include: keystone.yml
  - include: glance.yml
  - include: network-nodes.yml
  - include: cinder-nodes.yml
  - include: controller-nodes.yml
  - include: compute-nodes.yml
