---
  - include: logstash.yml
  - include: database.yml
  - include: messaging.yml
  - include: keystone-nodes.yml
  - include: glance-nodes.yml
  - include: network-nodes.yml
  - include: mpio.yml
  - include: cinder-nodes.yml
  - include: controller-nodes.yml
  - include: compute-nodes.yml
  - include: reboot-all.yml
