- name: install cinder packages
  apt: name={{item}} state=present
  with_items:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - open-iscsi
    - python-cinderclient
    - tgt

- name: install cinder.conf
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf mode=0644
  notify:
    - restart cinder

- name: install cinder api-paste.ini
  template: src=api-paste.ini.j2 dest=/etc/cinder/api-paste.ini
  notify:
    - restart cinder

- name: create partition on selected device
  shell: echo "0," | sfdisk {{cinder_device}}
  when: ansible_devices.sdb is defined 
  #when: ansible_devices.sdb is defined and not ansible_devices.sdb.holders.mpath0 

- name: see if we have any cinder-volumes existing
  command: vgdisplay {{cinder_volume_group}}
  register: vgdisplay
  ignore_errors: yes

- name: create cinder volume group
  lvg: pvs={{cinder_device}}-part1 vg={{cinder_volume_group}} state=present force=yes
  when: vgdisplay.rc != 0
  notify:
    - restart cinder
