- name: install packages for add-apt-repository
  apt: name={{item}} state=present
  with_items:
    - python-software-properties
    - software-properties-common

- name: install apt-key for mariadb
  apt_key: state=present data="{{ lookup('file', 'gpgkey.asc') }}"

- name: add mariadb repository
  apt_repository: state=present repo="deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main"

- name: apt update
  apt: update_cache=yes

- name: install mariadb with galera and client
  apt: name={{item}} state=present
  with_items:
    - mariadb-galera-server
    - mariadb-client

- name: install python-mysqldb
  apt: name=python-mysqldb state=present

- name: install our slightly modified my.cnf
  template: dest=/etc/mysql/my.cnf src=my.cnf.j2 

- name: ensure mariadb is (re)started and enabled
  service: name=mysql state=restarted enabled=yes

- name: give the database a couple seconds to settle
  command: sleep 2

- name: create database root user and password
  command: creates=/root/.my.cnf mysqladmin -u ${db_root_user} password ${db_root_pw}

- name: create .my.cnf for root
  template: src=dot_my.cnf.j2 dest=/root/.my.cnf mode=0600

