- name: install packages for add-apt-repository
  apt: name={{item}} state=present
  with_items:
    - python-software-properties
    - software-properties-common

- name: install apt-key for mariadb
  apt_key: state=present data="{{ lookup('file', 'gpgkey.asc') }}"

- name: add mariadb repository
  apt_repository: state=present repo="deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main"

- name: apt update
  apt: update_cache=yes

#- name: ensure conficting mysql packages aren't there
#  apt: name={{item}} state=absent
#  with_items:
#    - libmysqlclient18
#    - mysql-common
#    - python-mysqldb
#    - mysql-server-core-5.1
#    - mysql-client-5.1

- name: install mariadb with galera and client
  apt: name={{item}} state=present
  with_items:
    - libmysqlclient18=5.5.33a+maria-1~precise
    - mysql-common=5.5.33a+maria-1~precise
    - mariadb-galera-server
    - mariadb-client

- name: install python-mysqldb
  apt: name=python-mysqldb state=present

- name: install our slightly modified my.cnf
  template: dest=/etc/mysql/my.cnf src=my.cnf.j2 

- name: ensure mariadb is (re)started and enabled
  service: name=mysql state=restarted enabled=yes

- name: give the database a couple seconds to settle
  command: sleep 2

#- name: check if we can get database status locally with no password
#  command: mysql --host {{db_host}} -u {{db_root_user}} -e "show status"
#  register: mysql_root_password_not_set
#  ignore_errors: yes

#- name: create .my.cnf for root
#  template: src=dot_my.cnf.j2 dest=/root/.my.cnf mode=0600

#- name: create database root user via local socket
#  mysql_user: name=root password={{db_root_pw}} state=present  priv=*.*:ALL host={{item}} login_unix_socket=/var/run/mysqld/mysqld.sock
#  with_items:
#    - $ansible_hostname
#    - 127.0.0.1
#    - ::1
#    - \%
#  when: mysql_root_password_not_set.rc == 0

- name: create glance database
  mysql_db: name={{glance_db}} state=present login_user={{db_root_user}} login_password={{db_root_pw}}

- name: create glance database user
  mysql_user: name=${glance_db_user} password=${glance_db_pw} state=present  priv=${glance_db}.*:ALL host={{item}} login_user={{db_root_user}} login_password={{db_root_pw}}
  with_items:
    - ${ansible_eth0.ipv4.address}
    - localhost
    - \%

- name: create keystone database
  mysql_db: name=${keystone_db} state=present login_user={{db_root_user}} login_password={{db_root_pw}}

- name: create keystone database user
  mysql_user: name=${keystone_db_user} password=${keystone_db_pw} host={{item}} state=present priv=${keystone_db}.*:ALL
  with_items:
    - ${ansible_eth0.ipv4.address}
    - ${keystone_host}
    - localhost
    - \%

- name: create nova database
  mysql_db: name=${nova_db} state=present

- name: create nova database user
  mysql_user: name=${nova_db_user} password=${nova_db_pw} state=present host={{item}} priv=${nova_db}.*:ALL login_user={{db_root_user}} login_password={{db_root_pw}}
  with_items:
    - ${ansible_eth0.ipv4.address}
    - localhost
    - \%

- name: create quantum database
  mysql_db: name=${quantum_db} state=present

- name: create quantum database user
  mysql_user: name=${quantum_db_user} password=${quantum_db_pw} state=present host={{item}} priv=${quantum_db}.*:ALL login_user={{db_root_user}} login_password={{db_root_pw}}
  with_items:
    - ${ansible_eth0.ipv4.address}
    - localhost
    - \%


