- name: install python-mysqldb
  apt: name=python-mysqldb state=present 

- name: install nova-compute packages
  apt: name={{item}} state=present
  with_items:
    - nova-compute

- name: copy nova.conf to compute nodes
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: copy nova-paste.ini to compute nodes
  template: src=nova-paste.ini.j2 dest=/etc/nova/nova-paste.ini

- name: copy api-paste.ini to compute nodes
  template: src=api-paste.ini.j2 dest=/etc/nova/api-paste.ini

- name: stop nova-compute services prior to initializing database
  service: name={{item}} state=stopped
  with_items:
    - nova-compute

- name: initialize nova database
  command: nova-manage db sync

- name: (re)start nova-compute services
  service: name={{item}} state=restarted
  with_items:
    - libvirt-bin
    - nova-compute

- name: copy openrc to /root
  template: src=openrc.j2 dest=/root/openrc mode=0600

- include: networking.yml
