- name: install cinder packages
  apt: name={{item}} state=present
  with_items:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - open-iscsi
    - python-cinderclient
    - tgt

- name: install cinder.conf
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf mode=0644
  notify:
    - restart cinder

- name: install cinder api-paste.ini
  template: src=api-paste.ini.j2 dest=/etc/cinder/api-paste.ini
  notify:
    - restart cinder

- name: ensure volume_api_class is set to cinder
  lineinfile: dest=/etc/nova/nova.conf regexp="^volume_api_class" line="volume_api_class=nova.volume.cinder.API"

- name: initialize cinder database
  command: cinder-manage db sync

- name: create /dev/sdb1
  shell: echo "0," | sfdisk /dev/sdb
  when: ansible_devices.sdb is defined and not ansible_devices.sdb.partitions is defined

- name: create cinder volume group
  lvg: pvs=/dev/sdb1 vg={{cinder_volume_group}} state=present
