- name: install nova-controller packages
  apt: name={{item}} state=present
  with_items:
    - nova-novncproxy
    - novnc
    - nova-api
    - nova-ajax-console-proxy
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-doc
    - nova-scheduler
    - nova-network

- name: copy nova.conf to compute nodes
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: copy nova-paste.ini to compute nodes
  template: src=nova-paste.ini.j2 dest=/etc/nova/nova-paste.ini

- name: copy api-paste.ini to compute nodes
  template: src=api-paste.ini.j2 dest=/etc/nova/api-paste.ini

- name: restart controller services to pick up configuration
  service: name={{item}} state=restarted
  with_items:
    - nova-novncproxy
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
    - nova-network

- include: dashboard.yml