- name: ensure required packages are installed
  action: apt name={{item}} state=present
  with_items:
    - ntp
    - bridge-utils

- name: use the cloud archive when running on 12.04
  apt: name=ubuntu-cloud-keyring state=present
  when: ansible_distribution_release == "precise"

- name: install the cloud archive sources 
  lineinfile: dest=/etc/apt/sources.list regexp="deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/grizzly main" line="deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/grizzly main" 
  when: ansible_distribution_release == "precise"

- name: apt update
  command: apt-get update