- name: create ~/.ssh
  file: path=${home}/.ssh state=directory mode=0700 owner=vince group=vince

- name: write ~/.ssh/authorized_keys
  lineinfile: create=yes dest=${home}/.ssh/authorized_keys mode=0600 line="${public_key}" regexp="ssh-dss.*" 

- name: change ownerships
  file: path=/home/vince/.ssh/authorized_keys owner=vince group=vince

- name: ensure ~root/.ssh exists
  file: path=/root/.ssh state=directory mode=0700 owner=root group=root

- name: add my public key to root's authorized_keys
  lineinfile: dest=/root/.ssh/authorized_keys create=yes owner=root group=root mode=0600 line="${public_key}" regexp="ssh-dss.*vince$"
