- name: install nova-controller packages
  apt: name={{item}} state=present
  with_items:
    - nova-novncproxy
    - novnc
    - nova-api
    - nova-ajax-console-proxy
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-doc
    - nova-scheduler
    - python-novaclient
#    Keep nova-network around in case quantum/neutron doesn't work out
#    - nova-network

- name: install nova.conf
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: copy api-paste.ini 
  template: src=api-paste.ini.j2 dest=/etc/nova/api-paste.ini

- name: restart controller services to pick up configuration
  service: name={{item}} state=restarted
  with_items:
    - nova-novncproxy
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
#    Keep nova-network around in case quantum/neutron doesn't work out
#    - nova-network

- include: dashboard.yml
