- name: create keystone database
  mysql_db: name=${keystone_db} state=present

- name: create keystone database user
  mysql_user: name=${keystone_db_user} password=${keystone_db_pw} host={{item}} state=present priv=${keystone_db}.*:ALL
  with_items:
    - ${ansible_eth0.ipv4.address}
    - localhost
    - \%

