# collect facts from all nodes
#
- hosts: database_servers
  user: root
  tasks:
    - name: get facts so we can use hostvars in the next play
      setup:

# only needs to be run from one node of the cluster.
- hosts: database_servers[0]
  user: root
  roles:
    - database
