- hosts: database_servers
  user: root
  roles:
    - galera-common

# start up the first node, bootstrapping a new cluster
- hosts: database_servers[0]
  user: root
  roles:
    - galera-bootstrap
#    - galera-sysbench

# start up the other nodes, joining the cluster
- hosts: database_servers[1]:database_servers[2]
  user: root
  roles:
    - galera-nodes
#    - galera-sysbench
