- hosts: keystone_nodes
  user: root
  roles:
    - common
    - keystone

- hosts: keystone_nodes[0]
  user: root
  tasks:
  - name: initialize the new keystone database
    command: keystone-manage db_sync

  - name: restart keystone again to complete configuration changes
    service: name=keystone state=restarted

  - name: create initial roles
    command: /root/initial_data.sh
    environment: keystone_data

- hosts: keystone_nodes
  user: root
  tasks:
  - name: restart keystone
    service: name=keystone state=restarted
