- name: install keepalived
  apt: name=keepalived state=present

- name: ensure non-local IPs can be bound
  lineinfile: dest=/etc/sysctl.conf regexp="net.ipv4.ip_nonlocal_bind" line="net.ipv4.ip_nonlocal_bind=1"
  notify:
  - reload sysctl

- name: copy keepalived.conf 
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf mode=0644 owner=root group=root

- name: install haproxy
  apt: name=haproxy state=present
  notify: restart haproxy

- name: install haproxy.cfg
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0600 owner=haproxy group=haproxy
  notify: restart haproxy

- name: enable haproxy
  lineinfile: regexp="^ENABLED=" line="ENABLED=1" dest=/etc/default/haproxy state=present
  notify: restart haproxy
