- name: install multipath-tools and sg3-utils
  apt: name={{item}} state=present
  with_items:
    - multipath-tools
    - sg3-utils
  when: enable_mpio is true

- name: install multipath.conf
  template: dest=/etc/multipath.conf src=multipath.conf.j2
  register: multipath_conf
  when: enable_mpio is true

- name: restart multpath-tools
  service: name=multipath-tools state=restarted
  when: multipath_conf.changed == True
  when: enable_mpio is true

- name: grab the multipath -ll output
  command: multipath -ll -v2
  register: multipath_ll
  when: enable_mpio is true

- name: debug multipath output
  debug: msg={{multipath_ll.stdout_lines}}
  when: enable_mpio is true
